#define CLRUI 0  	/* TREE */
#define MONOUI 1  	/* TREE */
#define CTICK 2  	/* OBJECT in TREE #0 */
#define CCROSS 3  	/* OBJECT in TREE #0 */
#define CDOT 4  	/* OBJECT in TREE #0 */
#define CCIRC 5  	/* OBJECT in TREE #0 */
#define CDFLT 6  	/* OBJECT in TREE #0 */
#define MTICK 2  	/* OBJECT in TREE #1 */
#define MCROSS 3  	/* OBJECT in TREE #1 */
#define MDOT 4  	/* OBJECT in TREE #1 */
#define MCIRC 5  	/* OBJECT in TREE #1 */
#define MDFLT 6  	/* OBJECT in TREE #1 */
